<a href="https://colab.research.google.com/github/VsAthul/Fun-with-Jupyter/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sample Decision Tree **Program**

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [40]:
from google.colab import files
upload = files.upload()

Saving dataset_for_stroke_prediction.csv to dataset_for_stroke_prediction (2).csv

In [43]:
data = pd.read_csv('dataset_for_stroke_prediction.csv')
data.head()

      id  gender   age  ...   bmi   smoking_status stroke
0   9046    Male  67.0  ...  36.6  formerly smoked      1
1  51676  Female  61.0  ...   NaN     never smoked      1
2  31112    Male  80.0  ...  32.5     never smoked      1
3  60182  Female  49.0  ...  34.4           smokes      1
4   1665  Female  79.0  ...  24.0     never smoked      1

[5 rows x 12 columns]

In [44]:
data.shape

(5110, 12)

In [46]:
data.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [48]:
data['bmi'].replace(np.nan, data['bmi'].mean(), inplace=True)

/tmp/ipython-input-3721059847.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['bmi'].replace(np.nan, data['bmi'].mean(), inplace=True)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                5110 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [50]:
data.head()

      id  gender   age  ...        bmi   smoking_status stroke
0   9046    Male  67.0  ...  36.600000  formerly smoked      1
1  51676  Female  61.0  ...  28.893237     never smoked      1
2  31112    Male  80.0  ...  32.500000     never smoked      1
3  60182  Female  49.0  ...  34.400000           smokes      1
4   1665  Female  79.0  ...  24.000000     never smoked      1

[5 rows x 12 columns]

In [53]:
category_names = data.select_dtypes('object').columns.tolist()
le = LabelEncoder()
for x in category_names:
  data[x]= le.fit_transform(data[x])
data

         id  gender   age  ...        bmi  smoking_status  stroke
0      9046       1  67.0  ...  36.600000               1       1
1     51676       0  61.0  ...  28.893237               2       1
2     31112       1  80.0  ...  32.500000               2       1
3     60182       0  49.0  ...  34.400000               3       1
4      1665       0  79.0  ...  24.000000               2       1
...     ...     ...   ...  ...        ...             ...     ...
5105  18234       0  80.0  ...  28.893237               2       0
5106  44873       0  81.0  ...  40.000000               2       0
5107  19723       0  35.0  ...  30.600000               2       0
5108  37544       1  51.0  ...  25.600000               1       0
5109  44679       0  44.0  ...  26.200000               0       0

[5110 rows x 12 columns]

In [54]:
data.corr()['stroke']

id                   0.006388
gender               0.008929
age                  0.245257
hypertension         0.127904
heart_disease        0.134914
ever_married         0.108340
work_type           -0.032316
Residence_type       0.015458
avg_glucose_level    0.131945
bmi                  0.038947
smoking_status       0.028123
stroke               1.000000
Name: stroke, dtype: float64

In [56]:
features = data[["age","hypertension","heart_disease","avg_glucose_level"]]
features

       age  hypertension  heart_disease  avg_glucose_level
0     67.0             0              1             228.69
1     61.0             0              0             202.21
2     80.0             0              1             105.92
3     49.0             0              0             171.23
4     79.0             1              0             174.12
...    ...           ...            ...                ...
5105  80.0             1              0              83.75
5106  81.0             0              0             125.20
5107  35.0             0              0              82.99
5108  51.0             0              0             166.29
5109  44.0             0              0              85.28

[5110 rows x 4 columns]

In [57]:
x=features
y=data['stroke']

In [58]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.2, random_state=40)

In [59]:
model = DecisionTreeClassifier(criterion='entropy', max_depth=4)
model.fit(xtrain,ytrain)
pred = model.predict(xtest)
print("Accuracy : ", accuracy_score(ytest, pred))

Accuracy :  0.9510763209393346